version: "3"
services:
  postgres:
    image: "postgres:14"
    environment:
      - POSTGRES_PASSWORD=
  redis:
    image: "redis:6.0"
  client:
    image: "przemr/fibservice:fib-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "przemr/fibservice:fib-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=
      - REDIS_PORT=
      - PGUSER=
      - PGHOST=
      - PGDATABASE=
      - PGPASSWORD=
      - PGPORT=
  worker:
    image: "przemr/fibservice:fib-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=
      - REDIS_PORT=
  nginx:
    image: "przemr/fibservice:fib-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
